'================================================================================
'D:\WebShare\wwwroot\Index\Work\NASA.inc.asp Generated 11/27/2003 10:42:39 PM by WebUIdx.uRefresh...
Sub iNASA_Menu(x, y)
	Menu.RemoveAllItems()
	Ad "3508", "Astronomy", "", "0"
	Ad "3509", "Astronomy Picture of the Day Archive", "http://antwrp.gsfc.nasa.gov/apod/archivepix.html", "3508"
	Ad "3517", "Hubble Space Telescope", "", "3508"
	Ad "3521", "Deep Field Full Mosaic", "http://oposite.stsci.edu/pubinfo/PR/96/01/MosaicFull.jpg", "3517"
	Ad "3518", "Space Telescope Science Institute", "http://www.stsci.edu/top.html", "3517"
	Ad "3520", "STScI-HST Pictures", "http://oposite.stsci.edu/pubinfo/Pictures.html", "3517"
	Ad "3519", "STScl-HST Animations/Movies", "http://oposite.stsci.edu/pubinfo/Anim.html", "3517"
	Ad "3513", "KFWB Webservice Space Page", "http://www.kfwb.com/nnspac.html", "3508"
	Ad "3527", "NSSDC - National Science Space Data Center", "", "3508"
	Ad "3528", "NSSDC - National Science Space Data Center", "http://nssdc.gsfc.nasa.gov/", "3527"
	Ad "3529", "NSSDC Photo Gallery", "http://nssdc.gsfc.nasa.gov/photo_gallery/", "3527"
	Ad "3510", "Spacelink - Our Solar System", "http://spacelink.msfc.nasa.gov/Instructional.Materials/NASA.Educational.Products/Solar.System.Lithograph.Set/Our.Solar.System/.index.html", "3508"
	Ad "3512", "The Nine Planets - Images", "http://seds.lpl.arizona.edu/billa/tnp/nineplanets.html", "3508"
	Ad "2630", "Goddard Space Flight Center", "http://www.gsfc.nasa.gov/GSFC_homepage.html", "0"
	Ad "3522", "Human Spaceflight", "http://spaceflight.nasa.gov/index-m.html", "0"
	Ad "2296", "In Search Of... - NASA Live CAMs", "http://www.in-search-of.com/frames/nasa/nasacams.shtml", "0"
	Ad "2307", "JPL - Jet Propulsion Laboratory", "", "0"
	Ad "2310", "Mars", "http://pds.jpl.nasa.gov/planets/welcome/mars.htm", "2307"
	Ad "2308", "NASA Jet Propulsion Laboratory", "http://jpl.nasa.gov/", "2307"
	Ad "2311", "Radar Imaging", "http://southport.jpl.nasa.gov/index.html", "2307"
	Ad "2309", "Welcome to the Planets", "http://pds.jpl.nasa.gov/planets/welcome.htm", "2307"
	Ad "2656", "JSC Digital Image Collection", "http://images.jsc.nasa.gov/", "0"
	Ad "3531", "Kennedy Space Center", "http://www.ksc.nasa.gov/", "0"
	Ad "3514", "Ken's Stuff", "", "0"
	Ad "3515", "Ken's NASA Page", "/NASA/Welcome.htm", "3514"
	Ad "3516", "Local Image Archive", "/NASA/Images/", "3514"
	Ad "3501", "Mars", "", "0"
	Ad "3502", "Mars ", "http://pds.jpl.nasa.gov/planets/welcome/mars.htm", "3501"
	Ad "3503", "Mars Pathfinder", "http://entertainment.digital.com/mars/JPL/default1.html", "3501"
	Ad "3504", "Mars Picture List", "http://seds.lpl.arizona.edu/billa/tnp/pxmars.html", "3501"
	Ad "3505", "Mars Virtual Spacecraft - VR", "http://ic-www.arc.nasa.gov/ic/projects/bayes-group/Atlas/Mars/VSC/views/entrance/entrance.html", "3501"
	Ad "3506", "Virtual spacecraft boarding", "http://ic-www.arc.nasa.gov/ic/projects/bayes-group/Atlas/Mars/VSC/views/entrance/entrance.html", "3501"
	Ad "3343", "NASA", "http://www.nasa.gov/", "0"
	Ad "2634", "NOAA", "http://www.noaa.gov/", "0"
	Ad "2303", "Project Apollo", "", "0"
	Ad "3507", "Additional Information on Apollo-13", "http://www.ksc.nasa.gov/history/apollo/apollo-13/apollo-13-info.html", "2303"
	Ad "2304", "Apollo 11", "http://www.ksc.nasa.gov/history/apollo/apollo-11/apollo-11.html", "2303"
	Ad "3530", "Apollo-13", "http://www.ksc.nasa.gov/history/apollo/apollo-13/apollo-13.html", "2303"
	Ad "2302", "KSC - Project Apollo", "http://www.ksc.nasa.gov/history/apollo/apollo.html", "2303"
	Ad "2306", "NASM Apollo Page", "http://www.nasm.edu/APOLLO/", "2303"
	Ad "5041", "Publications", "", "0"
	Ad "5042", "NASA History Series Publications", "http://www.hq.nasa.gov/office/pao/History/series95.html", "5041"
	Ad "5043", "pdf", "http://www.hq.nasa.gov/office/pao/History/hhrhist.pdf", "5041"
	Ad "2312", "The Space Movie Archive", "", "0"
	Ad "2320", "Astronomical Pictures & Animations", "http://graffiti.u-bordeaux.fr/MAPBX/roussel/astro.english.html", "2312"
	Ad "2318", "Bordeaux", "http://graffiti.u-bordeaux.fr/MAPBX/roussel/anim-ewf.html", "2312"
	Ad "2317", "Gateway", "http://graffiti.u-bordeaux.fr/MAPBX/roussel/anim-e.html", "2312"
 
	Menu.Popup x, y
End Sub
'=============================================================================
