'================================================================================
'D:\WebShare\wwwroot\Index\Work\SciFi.inc.asp Generated 11/27/2003 10:42:43 PM by WebUIdx.uRefresh...
Sub iSciFi_Menu(x, y)
	Menu.RemoveAllItems()
	Ad "2208", "Battlestar Galactica", "", "0"
	Ad "4242", "Battlestar Galactica SFB and Friends", "http://www.bus.bton.ac.uk/staff/fesg/games/bsg/index.html", "2208"
	Ad "2213", "Chris Pappas Collection", "http://www.chrispappas.com/Galactica/", "2208"
	Ad "2209", "Ken's Battlestar Galactica Page", "/SciFi/BattlestarGalactica/BattlestarGalactica.asp", "2208"
	Ad "2212", "Mark Heiman's Battlestar Galactica Archives", "http://mcmfh.acns.carleton.edu/BG/", "2208"
	Ad "2211", "Richard Hatch's Galactica Page", "http://www9.pair.com/iwc/RichardHatch/battlestar.html", "2208"
	Ad "2210", "Sci-Fi Channel's Colonial Data Bank", "http://www.scifi.com/galactica/galix.html", "2208"
	Ad "2398", "The Home of Battlestar Galactica", "http://www.kobol.com/", "2208"
	Ad "2231", "Fantasy Art", "", "0"
	Ad "2232", "Dean, Roger", "/SciFi/Fantasy%20Art/Roger%20Dean/", "2231"
	Ad "2240", "Fantasy Picture Archive", "http://effie.osir.hihm.no/~missing/archive/fantasy/index.html", "2231"
	Ad "2233", "Frazetta, Frank", "/SciFi/Fantasy%20Art/Frank%20Frazetta/", "2231"
	Ad "2239", "Glass Onion Graphics", "http://www.glassonion.com/", "2231"
	Ad "2234", "Hildebrandt, Brothers", "/SciFi/Fantasy%20Art/Hildebrandt/", "2231"
	Ad "2235", "Matthews, Rodney", "/SciFi/Fantasy%20Art/Rodney%20Matthews/", "2231"
	Ad "2236", "Sweet, Darrell", "/SciFi/Fantasy%20Art/Darrell%20Sweet/", "2231"
	Ad "4990", "THE OFFICIAL PAPER TIGER WEB SITE", "http://www.papertiger.co.uk/", "2231"
	Ad "4986", "The Official Rodney Matthews Website", "http://www.rodneymatthews.com/", "2231"
	Ad "2237", "Vallejo, Boris", "/SciFi/Fantasy%20Art/Boris%20Vallejo/", "2231"
	Ad "2238", "Whelan, Michael", "/SciFi/Fantasy%20Art/Michael%20Whelan/artbooks.htm", "2231"
	Ad "2207", "Ken's Sci-Fi Image Archive", "/SciFi/", "0"
	Ad "2452", "Ken's SciFi Model Inventory", "/Hobby/SciFiModelsList.asp", "0"
	Ad "2214", "Space: Above && Beyond", "", "0"
	Ad "2713", "Above and Beyond News && Reviews by Kate 'Doc' Duncan", "http://www.planetx.com/~kduncan/", "2214"
	Ad "2334", "Local Version of the Defunct Fox Site", "/SAAB/spcindx.htm", "2214"
	Ad "2712", "Lubach's SPACE, ABOVE && BEYOND Page", "http://pobox.leidenuniv.nl/~alubach/saab2.htm", "2214"
	Ad "2335", "SAAB Mission Status", "http://www.microserve.net/space:aab/", "2214"
	Ad "2336", "SAAB Multimedia Site", "http://rampages.onramp.net/~brummett/space.htm", "2214"
	Ad "2407", "Space: Above && Beyond Web Ring", "http://www.webring.org/cgi-bin/webring?ring=space&list", "2214"
	Ad "2408", "Squad Bay's SAAB Site", "http://agate.net/~chazmanb/Bay.html", "2214"
	Ad "2711", "The Shane Vansen Shrine", "http://www.inman.mcmail.com/vansen.html", "2214"
	Ad "2338", "Star Trek", "", "0"
	Ad "2337", "Absolut Star Trek", "http://www.solace.mh.se/~el302/startrek/enter.html", "2338"
	Ad "2369", "Adam Star's Star Trek Site (UK)", "http://www.chem.ed.ac.uk/adamstar.html", "2338"
	Ad "4710", "Internet - The Starship Encyclopedia", "http://www.pacificnet.net/~filmman/starships/", "2338"
	Ad "2340", "Paramount Studios", "http://www.paramount.com/startrek/", "2338"
	Ad "2341", "Picture Archives", "http://tos-www.tos.net/services/services.html", "2338"
	Ad "2215", "Star Trek Image Archive", "/SciFi/StarTrek/StarTrek.htm", "2338"
	Ad "2367", "Star Trek: CONTINUUM", "http://www.startrek.com/", "2338"
	Ad "2394", "Starfleet International", "http://www.sfi.org/", "2338"
	Ad "2368", "Starfleet On-Line Encyclopedia", "http://ourworld.compuserve.com/homepages/space_the_final_frontier/encyc.htm", "2338"
	Ad "4711", "Starship Schematic Database", "http://www.shipschematics.net/", "2338"
	Ad "2342", "Starships Registry", "http://www.imagin.net/~rbklugh/registry.html", "2338"
	Ad "3720", "The Guide to Star Trek Ships", "http://www.geocities.com/Area51/Shadowlands/5216/index.html", "2338"
	Ad "4744", "Utopia Planitia Starfleet Yards @ Mars", "http://192.234.159.2/~utopia/", "2338"
	Ad "2339", "Star Wars", "", "0"
	Ad "2636", "Corellian Vessels", "http://www.synicon.com.au/sw/br/corellia.htm", "2339"
	Ad "2374", "El Reaper's Starwars Movie Archive", "http://www.lightlink.com/reaper/mov.htm", "2339"
	Ad "3450", "JediNet", "http://www.jedinet.com/", "2339"
	Ad "2375", "Links to The Star Wars Galaxy", "http://funnelweb.utcc.utk.edu/~crhawkns/swlinks.html", "2339"
	Ad "2370", "Lucas Arts", "http://www.lucasarts.com/", "2339"
	Ad "3448", "LucasFan.com", "http://www.lucasfan.com/", "2339"
	Ad "2376", "Max Rebo's Page", "http://www.ntr.net/~pbsoft/starwars/", "2339"
	Ad "3453", "Mike's Star Wars Site", "http://www.ece.orst.edu/~volzmi/starwars/", "2339"
	Ad "2377", "Nate's Star Wars Page", "http://www.mines.edu/students/n/nkruse/sw.html", "2339"
	Ad "2371", "New Republic Fleet Yards", "http://mmm.mbhs.edu/~dchen/starwars/fleetyards/fleetyards.html", "2339"
	Ad "3454", "Robert Vonhogen’s Virtual Edition", "http://www.virtualedition.com/", "2339"
	Ad "2372", "Rogue Squadron", "http://www.geocities.com/Colosseum/Field/4427/", "2339"
	Ad "2373", "Star Wars Home Page at UPENN", "http://www.stwing.upenn.edu/~jruspini/starwars.html/", "2339"
	Ad "2378", "Star Wars HUB", "http://empire.res.wabash.edu/index2.htm", "2339"
	Ad "2216", "Star Wars Image Archive", "/SciFi/StarWars/", "2339"
	Ad "5116", "Star Wars Multimedia Vault", "http://lavender.fortunecity.com/casablanca/95/mm.htm", "2339"
	Ad "2379", "Star Wars Trilogy Official Website", "http://www.starwars.com/home", "2339"
	Ad "3455", "StarWarz", "http://www.starwarz.com/", "2339"
	Ad "2380", "Steve's Star Wars Links", "http://www.relia.net/~bravhaart/starwars/links.html", "2339"
	Ad "3452", "The Prequels.com", "http://theprequels.com/", "2339"
	Ad "3451", "The Star Wars Database", "http://www.swdatabase.com/", "2339"
	Ad "2381", "The Star Wars VRML Page", "http://www.voicenet.com/~peso/starwars/VRML.htm", "2339"
	Ad "2382", "The Ultimate Star Wars-Sci-Fi Multimedia Vault", "http://www2.epix.net/~fnglk/sci-fi.html", "2339"
	Ad "3449", "TheForce.net", "http://www.theforce.net/", "2339"
	Ad "2383", "TimeLine", "http://www.evan.org/timeline.html", "2339"
	Ad "5223", "Stargate", "", "0"
	Ad "5225", "MGM TV Superstore", "http://www.mgmtvsuperstore.com/", "5223"
	Ad "5224", "STARGATE SG-1", "http://www.showtimeonline.com/stargate/mainframe.cgi", "5223"
	Ad "2399", "Starship Troopers", "http://www.localnet.com/~jweigl/excitement.html", "0"
	Ad "2400", "Stingray Memorabilia Museum", "http://www.marineville.com/", "0"
	Ad "2217", "The Sci-Fi Channel", "", "0"
	Ad "2219", "FreeZone", "http://www.scifi.com/freezone/video.html", "2217"
	Ad "2220", "Other Sci-Fi Channel Stuff", "/SciFi/SciFi%20Channel/", "2217"
	Ad "2218", "The Dominion (Sci-Fi Channel Home)", "http://www.scifi.com/", "2217"
	Ad "2401", "The Space- 1999 Cyber Museum", "http://space1999.net/", "0"
	Ad "2226", "The Space Movie Archive", "", "0"
	Ad "2230", "Astronomical Pictures & Animations", "http://graffiti.u-bordeaux.fr/MAPBX/roussel/astro.english.html", "2226"
	Ad "2228", "Bordeaux", "http://graffiti.u-bordeaux.fr/MAPBX/roussel/anim-ewf.html", "2226"
	Ad "2227", "Gateway", "http://graffiti.u-bordeaux.fr/MAPBX/roussel/anim-e.html", "2226"
	Ad "2221", "The X-Files", "", "0"
	Ad "2222", "Fox's The X-Files Home Page", "http://www.thex-files.com/", "2221"
	Ad "2225", "Trust No 1", "http://www.tcfhe.com/trustno1/index.html", "2221"
	Ad "2631", "Upcoming Episodes", "http://www.thex-files.com/upepis.htm", "2221"
 
	Menu.Popup x, y
End Sub
'=============================================================================
