//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TC3EF6.WebForms.Books {
    
    
    public partial class BooksListAjax_1__7__2 {
    }
}
