<script language="VBScript" runat="Server">
'============================================================================

Function GetRandom(LowerBound, UpperBound)
  Randomize
  GetRandom = Int((UpperBound - LowerBound + 1) * Rnd + LowerBound)
End Function
'============================================================================
Function GetSongURL()
	Dim MIDI
	Dim Songs()
	Dim i
	
	Select Case GetRandom(0, 44)
		Case 0
			ReDim Songs(4)
			Songs(0) = "clardlun.mid"
			Songs(1) = "CocaCola.mid"
			Songs(2) = "greensle.mid"
			Songs(3) = "tennwalz.mid"
			MIDI = "/Sounds/MIDI/" & Songs(GetRandom(0, 3))
		Case 1
			ReDim Songs(3)
			Songs(0) = "Dancing Queen.mid"
			Songs(1) = "Fernando.mid"
			Songs(2) = "Knowing Me Knowing You.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/ABBA/" & Songs(GetRandom(0, 2))
		Case 2
			ReDim Songs(2)
			Songs(0) = "Eye In The Sky.mid"
			Songs(1) = "Old & Wise.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Alan Parsons Project/" & Songs(GetRandom(0, 1))
		Case 3
			ReDim Songs(3)
			Songs(0) = "Don't Cry.mid"
			Songs(1) = "Heat Of The Moment.mid"
			Songs(2) = "Only Time Will Tell.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Asia/" & Songs(GetRandom(0, 2))
		Case 4
			ReDim Songs(38)
			Songs(0) = "52nd Street.mid"
			Songs(1) = "A Matter Of Trust.mid"
			Songs(2) = "An Innocent Man.mid"
			Songs(3) = "Angry Young Man.mid"
			Songs(4) = "Baby Grand.mid"
			Songs(5) = "Big Man On Mulberry Street.mid"
			Songs(6) = "Big Shot.mid"
			Songs(7) = "Blonde Over Blue.mid"
			Songs(8) = "Captain Jack.mid"
			Songs(9) = "Close To The Borderline.mid"
			Songs(10) = "Don't Ask Me Why.mid"
			Songs(11) = "Famous Last Words.mid"
			Songs(12) = "Honesty.mid"
			Songs(13) = "It's Still Rock And Roll To Me.mid"
			Songs(14) = "Just The Way You Are.mid"
			Songs(15) = "Leningrad.mid"
			Songs(16) = "Lullabye (Goodnight, My Angel).mid"
			Songs(17) = "Movin' Out (Anthony's Song).mid"
			Songs(18) = "My Life.mid"
			Songs(19) = "New York State Of Mind.mid"
			Songs(20) = "Nocturne.mid"
			Songs(21) = "Piano Man (Classical Version).mid"
			Songs(22) = "Piano Man.mid"
			Songs(23) = "Pressure.mid"
			Songs(24) = "River of Dreams.mid"
			Songs(25) = "Root Beer Rag.mid"
			Songs(26) = "Running On Ice.mid"
			Songs(27) = "Shameless.mid"
			Songs(28) = "She's Got A Way.mid"
			Songs(29) = "Stiletto.mid"
			Songs(30) = "Temptation.mid"
			Songs(31) = "The Longest Time.mid"
			Songs(32) = "The Mexican Connection.mid"
			Songs(33) = "The River Of Dreams.mid"
			Songs(34) = "The Stranger.mid"
			Songs(35) = "This Is The Time.mid"
			Songs(36) = "Uptown Girl.mid"
			Songs(37) = "We Can't Stop The Fire.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Billy Joel/" & Songs(GetRandom(0, 37))
		Case 5
			ReDim Songs(3)
			Songs(0) = "Call Me.mid"
			Songs(1) = "Heart Of Glass.mid"
			Songs(2) = "Rapture.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Blondie/" & Songs(GetRandom(0, 3))
		Case 6
			ReDim Songs(5)
			Songs(0) = "Don't Look Back.mid"
			Songs(1) = "Foreplay-Long Time.mid"
			Songs(2) = "Long Time (Revised).mid"
			Songs(3) = "More Than A Feeling.mid"
			Songs(4) = "Piece Of Mind.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Boston/" & Songs(GetRandom(0, 4))
		Case 7
			ReDim Songs(6)
			Songs(0) = "Born In The U.S.A..mid"
			Songs(1) = "Born To Run.mid"
			Songs(2) = "Dancing In The Dark.mid"
			Songs(3) = "I'm On Fire.mid"
			Songs(4) = "Streets Of Philadelphia.mid"
			Songs(5) = "The River.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Bruce Springsteen/" & Songs(GetRandom(0, 5))
		Case 8
			ReDim Songs(11)
			Songs(0) = "Susie-Q.mid"
			Songs(1) = "Lookin' Out My Back Door.mid"
			Songs(2) = "Lodi.mid"
			Songs(3) = "Have You Ever Seen The Rain.mid"
			Songs(4) = "Green River.mid"
			Songs(5) = "Fortunate Son.mid"
			Songs(6) = "Down On The Corner.mid"
			Songs(7) = "Bad Moon Rising.mid"
			Songs(8) = "Who'll Stop The Rain.mid"
			Songs(9) = "backdoor.mid"
			Songs(10) = "Proud Mary.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/CCR/" & Songs(GetRandom(0, 10))
		Case 9
			ReDim Songs(8)
			Songs(0) = "Why Worry.mid"
			Songs(1) = "Walk Of Life.mid"
			Songs(2) = "Sultans Of Swing.mid"
			Songs(3) = "Money For Nothing.mid"
			Songs(4) = "Dire Straits.mid"
			Songs(5) = "Calling Elvis.mid"
			Songs(6) = "Brothers In Arms.mid"
			Songs(7) = "Private Investigations.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Dire Straits/" & Songs(GetRandom(0, 7))
		Case 10
			ReDim Songs(3)
			Songs(0) = "China Grove.mid"
			Songs(1) = "Long Train Running.mid"
			Songs(2) = "Takin' It To The Streets.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Doobie Brothers/" & Songs(GetRandom(0, 2))
		Case 11
			ReDim Songs(16)
			Songs(0) = "Desperado.mid"
			Songs(1) = "Try And Love Again.mid"
			Songs(2) = "Tequila Sunrise.mid"
			Songs(3) = "Seven Bridges Road.mid"
			Songs(4) = "Peaceful Easy Feeling.mid"
			Songs(5) = "Lyin' Eyes.mid"
			Songs(6) = "Life In The Fast Lane.mid"
			Songs(7) = "I Can't Tell You Why.mid"
			Songs(8) = "Hotel California.mid"
			Songs(9) = "Victim Of Love.mid"
			Songs(10) = "Best Of My Love.mid"
			Songs(11) = "Pretty Maids All In A Row.mid"
			Songs(12) = "New Kid In Town.mid"
			Songs(13) = "Love Will Always Keep Us Alive.mid"
			Songs(14) = "The Girl From Yesterday.mid"
			Songs(15) = "The Last Resort.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Eagles/" & Songs(GetRandom(0, 15))
		Case 12
			ReDim Songs(27)
			Songs(0) = "Believe.mid"
			Songs(1) = "Your Song.mid"
			Songs(2) = "The One.mid"
			Songs(3) = "Candle In The Wind.mid"
			Songs(4) = "Crocodile Rock.mid"
			Songs(5) = "I Guess That's Why They Call It The Blues.mid"
			Songs(6) = "Saturday Night's Alright for Fighting.mid"
			Songs(7) = "Your Sister Can't Twist (But She Can Rock 'N' Roll).mid"
			Songs(8) = "The Last Song.mid"
			Songs(9) = "The Bitch Is Back.mid"
			Songs(10) = "Take Me To The Pilot.mid"
			Songs(11) = "Sixty Years On.mid"
			Songs(12) = "Simple Life.mid"
			Songs(13) = "Rocket Man.mid"
			Songs(14) = "Philadelphia Freedom.mid"
			Songs(15) = "Goodbye Yellow Brick Road.mid"
			Songs(16) = "Funeral For A Friend & Love Lies Bleeding.mid"
			Songs(17) = "Empty Garden (Hey Hey Johnny).mid"
			Songs(18) = "Don't Let The Sun Go Down On Me.mid"
			Songs(19) = "Don't Go Breakin My Heart.mid"
			Songs(20) = "Daniel.mid"
			Songs(21) = "Crocodile Rock.mid"
			Songs(22) = "Can You Feel The Love Tonight.mid"
			Songs(23) = "Bennie And The Jets.mid"
			Songs(24) = "Sorry Seems To Be The Hardest Word.mid"
			Songs(25) = "The Circle Of Life.mid"
			Songs(26) = "Blue Eyes.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Elton John/" & Songs(GetRandom(0, 26))
		Case 13
			ReDim Songs(16)
			Songs(0) = "Bad Love.mid"
			Songs(1) = "Signe.mid"
			Songs(2) = "Running On Faith.mid"
			Songs(3) = "Rollin' & Tumblin'.mid"
			Songs(4) = "Rock N' Roll Heart.mid"
			Songs(5) = "Nobody Knows You When You're Down And Out.mid"
			Songs(6) = "Layla - Original.mid"
			Songs(7) = "Cocaine.mid"
			Songs(8) = "Badge.mid"
			Songs(9) = "Wonderful Tonight.mid"
			Songs(10) = "Sunshine Of My Love.mid"
			Songs(11) = "White Room.mid"
			Songs(12) = "I Shot The Sheriff.mid"
			Songs(13) = "Let It Grow.mid"
			Songs(14) = "Layla (Unplugged).mid"
			Songs(15) = "Tears In Heaven.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Eric Clapton/" & Songs(GetRandom(0, 15))
		Case 14
			ReDim Songs(3)
			Songs(0) = "Gypsy.mid"
			Songs(1) = "Little Lies.mid"
			Songs(2) = "Rhiannon.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Fleetwood Mac/" & Songs(GetRandom(0, 2))
		Case 15
			ReDim Songs(79)
			Songs(0) = "TonightTonightTonight.mid"
			Songs(1) = "Abacab.mid"
			Songs(2) = "Afterglw.mid"
			Songs(3) = "ATrickOfTheTail.mid"
			Songs(4) = "CarpetCrawlers.mid"
			Songs(5) = "DanceOnAVolcano.mid"
			Songs(6) = "Dodo-Lurker.mid"
			Songs(7) = "Firth5th.mid"
			Songs(8) = "FollowYouFollowMe.mid"
			Songs(9) = "That'sAll.mid"
			Songs(10) = "HomeByTheSea.mid"
			Songs(11) = "IKnowWhatILike.mid"
			Songs(12) = "jesus.mid"
			Songs(13) = "LambLiesDownOnBroadway.mid"
			Songs(14) = "LandOfConfusion.mid"
			Songs(15) = "Ripples.mid"
			Songs(16) = "Supper'sReady.mid"
			Songs(17) = "TheGrandParadeOfLifelessPackaging.mid"
			Songs(18) = "1-squonk.mid"
			Songs(19) = "Abacab (2).mid"
			Songs(20) = "Turn It On.mid"
			Songs(21) = "The Musical Box.mid"
			Songs(22) = "The Brazilian.mid"
			Songs(23) = "Tell Me Why.mid"
			Songs(24) = "Taking It All To Hard.mid"
			Songs(25) = "Squonk (2).mid"
			Songs(26) = "Paperlate (2).mid"
			Songs(27) = "One For The Vine.mid"
			Songs(28) = "No Son Of Mine (2).mid"
			Songs(29) = "Never A Time.mid"
			Songs(30) = "Misunderstanding.mid"
			Songs(31) = "Many Too Many.mid"
			Songs(32) = "Mad Man Moon.mid"
			Songs(33) = "Land Of Confusion.mid"
			Songs(34) = "Lamb Lies Down On Broadway.mid"
			Songs(35) = "Jesus He Knows Me.mid"
			Songs(36) = "Invisible Touch (2).mid"
			Songs(37) = "In Too Deep.mid"
			Songs(38) = "In The Cage Medley.mid"
			Songs(39) = "I Can't Dance.mid"
			Songs(40) = "Horizons (2).mid"
			Songs(41) = "Hold On My Heart.mid"
			Songs(42) = "Follow You, Follow Me (2).mid"
			Songs(43) = "Firth Of Fifth.mid"
			Songs(44) = "Driving The Last Spike.mid"
			Songs(45) = "Domino.mid"
			Songs(46) = "Carpet Crawlers.mid"
			Songs(47) = "Blood On The Rooftops.mid"
			Songs(48) = "Afterglow.mid"
			Songs(49) = "Watcher Of The Skies.mid"
			Songs(50) = "Tonight, Tonight, Tonight.mid"
			Songs(51) = "Mama.mid"
			Songs(52) = "Get 'Em Out By Friday.mid"
			Songs(53) = "The Knife.mid"
			Songs(54) = "The Return Of The Giant Hogweed.mid"
			Songs(55) = "A Trick Of The Tail.mid"
			Songs(56) = "The Grand Parade Of Lifeless Packaging.mid"
			Songs(57) = "That's All.mid"
			Songs(58) = "Lilywhite Lilith.mid"
			Songs(59) = "Home By The Sea.mid"
			Songs(60) = "Heathaze.mid"
			Songs(61) = "Fading Lights.mid"
			Songs(62) = "Duke's End.mid"
			Songs(63) = "Broadway Melody Of 1974.mid"
			Songs(64) = "Throwing It All Away.mid"
			Songs(65) = "Seven Stones.mid"
			Songs(66) = "All In A Mouse's Night.mid"
			Songs(67) = "The Lamia.mid"
			Songs(68) = "The Lady Lies.mid"
			Songs(69) = "Supper's Ready.mid"
			Songs(70) = "Snowbound.mid"
			Songs(71) = "I Know What I Like.mid"
			Songs(72) = "Hairless Heart.mid"
			Songs(73) = "Fountain Of Salmacis.mid"
			Songs(74) = "Dance On A Volcano.mid"
			Songs(75) = "Can-Utility And The Coastliners.mid"
			Songs(76) = "Anyway.mid"
			Songs(77) = "Time Table.mid"
			Songs(78) = "Battle of Epping Forest.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Genesis/" & Songs(GetRandom(0, 78))
		Case 16
			ReDim Songs(3)
			Songs(0) = "Fire And Rain.mid"
			Songs(1) = "Never Die Young.mid"
			Songs(2) = "How Sweet It Is.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/James Taylor/" & Songs(GetRandom(0, 2))
		Case 17
			ReDim Songs(4)
			Songs(0) = "Summer In The City.mid"
			Songs(1) = "Unchain My Heart.mid"
			Songs(2) = "The Letter.mid"
			Songs(3) = "With A Little Help From My Friends.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Joe Cocker/" & Songs(GetRandom(0, 3))
		Case 18
			ReDim Songs(8)
			Songs(0) = "Concert Medley.mid"
			Songs(1) = "Separate Ways (Worlds Apart).mid"
			Songs(2) = "Send Her My Love.mid"
			Songs(3) = "Open Arms.mid"
			Songs(4) = "Faithfully (2).mid"
			Songs(5) = "Don't Stop Believin'.mid"
			Songs(6) = "Who's Crying Now.mid"
			Songs(7) = "Don't Stop Til You Get Enough.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Journey/" & Songs(GetRandom(0, 7))
		Case 19
			ReDim Songs(11)
			Songs(0) = "Point Of Know Return.mid"
			Songs(1) = "Song For America.mid"
			Songs(2) = "Opus Insert.mid"
			Songs(3) = "The Spider.mid"
			Songs(4) = "Dust In The Wind.mid"
			Songs(5) = "Hopelessly Human.mid"
			Songs(6) = "Icarus - Borne On Wings Of Steel.mid"
			Songs(7) = "Journey From Mariabonn.mid"
			Songs(8) = "Magnum Opus.mid"
			Songs(9) = "Paradox.mid"
			Songs(10) = "Chasing Shadows.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Kansas/" & Songs(GetRandom(0, 10))
		Case 20
			ReDim Songs(45)
			Songs(0) = "Babe I'm Gonna Leave You.mid"
			Songs(1) = "Ten Years Gone.mid"
			Songs(2) = "Stairway To Heaven (Symphonic Version).mid"
			Songs(3) = "Stairway To Heaven (3).mid"
			Songs(4) = "No Quarter.mid"
			Songs(5) = "Moby Dick.mid"
			Songs(6) = "Kashmir.mid"
			Songs(7) = "Heartbreaker & Living, Loving Maid (She's Just a Woman) Medley.mid"
			Songs(8) = "Bring It On Home.mid"
			Songs(9) = "Boogie With Stu.mid"
			Songs(10) = "Black Dog.mid"
			Songs(11) = "Whole Lotta Love.mid"
			Songs(12) = "Dazed And Confused.mid"
			Songs(13) = "When The Levee Breaks.mid"
			Songs(14) = "Since I've Been Loving You.mid"
			Songs(15) = "Rock And Roll.mid"
			Songs(16) = "Misty Mountain Hop.mid"
			Songs(17) = "Immigrant Song.mid"
			Songs(18) = "How Many.mid"
			Songs(19) = "Good Times Bad Times.mid"
			Songs(20) = "Your Time Is Going To Come.mid"
			Songs(21) = "Communication Breakdown.mid"
			Songs(22) = "The Song Remains The Same.mid"
			Songs(23) = "The Lemon Song.mid"
			Songs(24) = "The Battle Of Evermore.mid"
			Songs(25) = "Ramble On.mid"
			Songs(26) = "Going To California.mid"
			Songs(27) = "What Is And What Should Never Be.mid"
			Songs(28) = "All My Love.mid"
			Songs(29) = "Over The Hills And Far Away.mid"
			Songs(30) = "Thank You.mid"
			Songs(31) = "Living Loving Maid (She's Just a Woman).mid"
			Songs(32) = "The Rain Song.mid"
			Songs(33) = "The Ocean.mid"
			Songs(34) = "Tangerine.mid"
			Songs(35) = "Hey Hey What Can I Do.mid"
			Songs(36) = "Gallows Pole.mid"
			Songs(37) = "Fool In The Rain.mid"
			Songs(38) = "D'yer Mak'er.mid"
			Songs(39) = "Custard Pie.mid"
			Songs(40) = "Bron-Y-Aur Stomp.mid"
			Songs(41) = "Black Mountain Side.mid"
			Songs(42) = "wholelot.mid"
			Songs(43) = "led1.mid"
			Songs(44) = "heaven.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Led Zeppelin/" & Songs(GetRandom(0, 44))
		Case 21
			ReDim Songs(2)
			Songs(0) = "Gimme Three Steps.mid"
			Songs(1) = "Sweet Home Alabama.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Lynyrd Skynyrd/" & Songs(GetRandom(0, 1))
		Case 22
			ReDim Songs(5)
			Songs(0) = "Word Of Mouth.mid"
			Songs(1) = "The Living Years.mid"
			Songs(2) = "Silent Running.mid"
			Songs(3) = "Another Cup Of Coffee.mid"
			Songs(4) = "All I Need Is A Miracle.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Mike & The Mechanics/" & Songs(GetRandom(0, 4))
		Case 23
			ReDim Songs(37)
			Songs(0) = "BillyIdol_WhiteWedding.mid"
			Songs(1) = "LittleFeat_DixieChicken.mid"
			Songs(2) = "EddieMoney_TwoTicketsToParadise.mid"
			Songs(3) = "Survivor_EyeOfTheTiger.mid"
			Songs(4) = "GoldenEarring_TwilightZone.mid"
			Songs(5) = "LookingGlass_Brandy.mid"
			Songs(6) = "LouiLoui.mid"
			Songs(7) = "CrashTestDummies_MmmMmm.mid"
			Songs(8) = "ProcolHarum_AWhiterShadeOfPale.mid"
			Songs(9) = "A-Ha_TakeOnMe.mid"
			Songs(10) = "VanHalen_Jump.mid"
			Songs(11) = "4Seasons_WhatANite.mid"
			Songs(12) = "DeepPurple_SmokeOnTheWater.mid"
			Songs(13) = "PaulSimon_CallMeAl.mid"
			Songs(14) = "NormanGreenbaum_SpiritInTheSky.mid"
			Songs(15) = "JohnnyNash_ICanSeeClearlyNow.mid"
			Songs(16) = "VanMorrison_BrownEyedGirl.mid"
			Songs(17) = "TheTrogs_WildThing.mid"
			Songs(18) = "CatStevens_WildWorld.mid"
			Songs(19) = "TheKinks_YouReallyGotMe.mid"
			Songs(20) = "IronButterfly_InAGaddaDaVida.mid"
			Songs(21) = "GratefulDead_WestLAFadeaway.mid"
			Songs(22) = "TheEdgarWinterGroup_Frankenstein.mid"
			Songs(23) = "Bachman-Turner-Overdrive_YouAin'tSeenNothingYet.mid"
			Songs(24) = "MenAtWork_DownUnder.mid"
			Songs(25) = "CuttingCrew_IJustDiedInYourArms.mid"
			Songs(26) = "JGeilsBand_Centerfold.mid"
			Songs(27) = "ThinLizzy_TheBoysAreBackInTown.mid"
			Songs(28) = "Queensryche_SilentLucidity.mid"
			Songs(29) = "SimpleMinds_Don'tYouForgetAboutMe.mid"
			Songs(30) = "SimpleMinds_AliveAndKicking.mid"
			Songs(31) = "Starship_WeBuiltThisCity.mid"
			Songs(32) = "TearsForFears_EverybodyWantsToRuleTheWorld.mid"
			Songs(33) = "TearsForFears_Shout.mid"
			Songs(34) = "Foreignor_Hot Blooded.mid"
			Songs(35) = "PaulMcCartney_Figure Of Eight.mid"
			Songs(36) = "UB40_Don't Worry Be Happy.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Miscellaneous/" & Songs(GetRandom(0, 36))
		Case 24
			ReDim Songs(12)
			Songs(0) = "Walk Through The Fire.mid"
			Songs(1) = "That Voice Again.mid"
			Songs(2) = "Steam.mid"
			Songs(3) = "Starless.mid"
			Songs(4) = "Solsbury Hill.mid"
			Songs(5) = "Sledgehammer.mid"
			Songs(6) = "Shock The Monkey.mid"
			Songs(7) = "Lead A Normal Life.mid"
			Songs(8) = "Humdrum.mid"
			Songs(9) = "Games Without Frontiers.mid"
			Songs(10) = "Don't Give Up.mid"
			Songs(11) = "Digging In The Dirt.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Peter Gabriel/" & Songs(GetRandom(0, 11))
		Case 25
			ReDim Songs(27)
			Songs(0) = "You Can't Hurry Love.mid"
			Songs(1) = "Two Hearts.mid"
			Songs(2) = "The West Side.mid"
			Songs(3) = "Take Me Home.mid"
			Songs(4) = "Sussudeo.mid"
			Songs(5) = "Something Happened On The Way To Heaven.mid"
			Songs(6) = "Saturday Night And Sunday Morning.mid"
			Songs(7) = "One More Night.mid"
			Songs(8) = "Inside Out.mid"
			Songs(9) = "In The Air Tonight.mid"
			Songs(10) = "I Wish It Would Rain Down.mid"
			Songs(11) = "Hang In Long Enough.mid"
			Songs(12) = "Groovy Kind Of Love.mid"
			Songs(13) = "Everyday.mid"
			Songs(14) = "Easy Lover.mid"
			Songs(15) = "Don't Lose My Number.mid"
			Songs(16) = "Do You Remember.mid"
			Songs(17) = "Another Day In Paradise.mid"
			Songs(18) = "Against All Odds (Take A Look At Me Now).mid"
			Songs(19) = "Long Long Way To Go.mid"
			Songs(20) = "Both Sides Of The Story.mid"
			Songs(21) = "The Same Moon.mid"
			Songs(22) = "Love Police.mid"
			Songs(23) = "It's In Your Eyes.mid"
			Songs(24) = "Dance Into The Light.mid"
			Songs(25) = "Wear My Hat.mid"
			Songs(26) = "Ricky.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Phil Collins/" & Songs(GetRandom(0, 26))
		Case 26
			ReDim Songs(23)
			Songs(0) = "Wots...Uh The Deal.mid"
			Songs(1) = "Wish You Were Here.mid"
			Songs(2) = "Vera.mid"
			Songs(3) = "Us And Them.mid"
			Songs(4) = "Time.mid"
			Songs(5) = "The Wall.mid"
			Songs(6) = "The Final Cut.mid"
			Songs(7) = "Shine On You Crazy Diamond.mid"
			Songs(8) = "Sheep.mid"
			Songs(9) = "On The Turning Away.mid"
			Songs(10) = "Nobody Home.mid"
			Songs(11) = "Money.mid"
			Songs(12) = "Keep Talking.mid"
			Songs(13) = "Is There Anybody Out There.mid"
			Songs(14) = "High Hopes.mid"
			Songs(15) = "Hey You.mid"
			Songs(16) = "Have A Cigar.mid"
			Songs(17) = "Great Gig In The Sky.mid"
			Songs(18) = "Echoes.mid"
			Songs(19) = "Comfortably Numb.mid"
			Songs(20) = "Breath In The Air.mid"
			Songs(21) = "Brain Damage.mid"
			Songs(22) = "The Trial.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Pink Floyd/" & Songs(GetRandom(0, 22))
		Case 27
			ReDim Songs(13)
			Songs(0) = "Wrapped Around Your Finger.mid"
			Songs(1) = "Walking On The Moon.mid"
			Songs(2) = "Spirits In The Material World.mid"
			Songs(3) = "Roxanne.mid"
			Songs(4) = "Message In A Bottle.mid"
			Songs(5) = "King Of Pain.mid"
			Songs(6) = "Get Here.mid"
			Songs(7) = "Every Little Thing She Does Is Magic.mid"
			Songs(8) = "Every Breath You Take.mid"
			Songs(9) = "Don't Stand So Close To Me.mid"
			Songs(10) = "De Do Do Do, De Da Da Da.mid"
			Songs(11) = "Can't Stand Losing You.mid"
			Songs(12) = "evbrth.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Police/" & Songs(GetRandom(0, 12))
		Case 28
			ReDim Songs(32)
			Songs(0) = "Another One Bites The Dust.mid"
			Songs(1) = "We Are The Champions.mid"
			Songs(2) = "The Miracle.mid"
			Songs(3) = "Innuendo.mid"
			Songs(4) = "Bohemian Rhapsody (2).mid"
			Songs(5) = "We Will Rock You.mid"
			Songs(6) = "All God's People.mid"
			Songs(7) = "Who Wants To Live Forever.mid"
			Songs(8) = "Under Pressure.mid"
			Songs(9) = "The Show Must Go On.mid"
			Songs(10) = "The Invisible Man.mid"
			Songs(11) = "Save Me.mid"
			Songs(12) = "Radio Gaga.mid"
			Songs(13) = "Killer Queen.mid"
			Songs(14) = "It's A Hard Life.mid"
			Songs(15) = "I'm Going Slightly Mad.mid"
			Songs(16) = "I Can't Live With You.mid"
			Songs(17) = "Headlong.mid"
			Songs(18) = "Good Old Fashioned Lover Boy.mid"
			Songs(19) = "Friends Will Be Friends.mid"
			Songs(20) = "Don't Try So Hard.mid"
			Songs(21) = "Days Of Our Lives.mid"
			Songs(22) = "Crazy Little Thing Called Love.mid"
			Songs(23) = "Breakthrough.mid"
			Songs(24) = "Bijou.mid"
			Songs(25) = "You're My Best Friend.mid"
			Songs(26) = "A Kind Of Magic.mid"
			Songs(27) = "One Vision.mid"
			Songs(28) = "My Friend.mid"
			Songs(29) = "Invisible Man.mid"
			Songs(30) = "Play The Game.mid"
			Songs(31) = "BohemianRhapsody.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Queen/" & Songs(GetRandom(0, 31))
		Case 29
			ReDim Songs(3)
			Songs(0) = "Can't Fight This Feeling.mid"
			Songs(1) = "In My Dreams.mid"
			Songs(2) = "Keep On Loving You.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/REO Speedwagon/" & Songs(GetRandom(0, 2))
		Case 30
			ReDim Songs(11)
			Songs(0) = "Weapon.mid"
			Songs(1) = "Vital Signs.mid"
			Songs(2) = "YYZ.mid"
			Songs(3) = "Tom Sawyer.mid"
			Songs(4) = "New World Man.mid"
			Songs(5) = "Subdivisions.mid"
			Songs(6) = "Roll The Bones.mid"
			Songs(7) = "Red Barchetta.mid"
			Songs(8) = "Mission.mid"
			Songs(9) = "Manhattan Project.mid"
			Songs(10) = "Limelight.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Rush/" & Songs(GetRandom(0, 10))
		Case 31
			ReDim Songs(7)
			Songs(0) = "Take The Money And Run.mid"
			Songs(1) = "Rock 'N Me.mid"
			Songs(2) = "Living In The U.S.A..mid"
			Songs(3) = "Joker.mid"
			Songs(4) = "Jet Airliner.mid"
			Songs(5) = "Fly Like An Eagle.mid"
			Songs(6) = "Abracadabra.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Steve Miller Band/" & Songs(GetRandom(0, 6))
		Case 32
			ReDim Songs(19)
			Songs(0) = "Consider Gone.mid"
			Songs(1) = "They Dance Alone.mid"
			Songs(2) = "The Soul Cages.mid"
			Songs(3) = "Straight To My Heart.mid"
			Songs(4) = "Shape Of My Heart.mid"
			Songs(5) = "Second Marriage.mid"
			Songs(6) = "Moon Bourbon.mid"
			Songs(7) = "If You Love Somebody.mid"
			Songs(8) = "If I Ever Lose My Faith In You (2).mid"
			Songs(9) = "Fragile (1).mid"
			Songs(10) = "Fields Of Gold (2).mid"
			Songs(11) = "Epilogue (Nothing 'Bout Me).mid"
			Songs(12) = "Englishman In New York (2).mid"
			Songs(13) = "We'll Be Together.mid"
			Songs(14) = "Mad About You.mid"
			Songs(15) = "Seven Days.mid"
			Songs(16) = "I Hung My Head.mid"
			Songs(17) = "Saint Agnes And The Burning Train.mid"
			Songs(18) = "Every Breath You Take.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Sting/" & Songs(GetRandom(0, 18))
		Case 33
			ReDim Songs(9)
			Songs(0) = "Too Much Time On My Hands.mid"
			Songs(1) = "The Grand Illusion.mid"
			Songs(2) = "The Best Of Times.mid"
			Songs(3) = "Mr. Roboto.mid"
			Songs(4) = "Fooling Yourself (The Angry Young Man).mid"
			Songs(5) = "Don't Let It End.mid"
			Songs(6) = "Come Sail Away.mid"
			Songs(7) = "Blue Collar Man (Long Nights).mid"
			Songs(8) = "Babe.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Styx/" & Songs(GetRandom(0, 8))
		Case 34
			ReDim Songs(2)
			Songs(0) = "Bloody Wel Right.mid"
			Songs(1) = "Take The Long Way Home.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Supertramp/" & Songs(GetRandom(0, 1))
		Case 35
			ReDim Songs(105)
			Songs(0) = "Across The Universe.mid"
			Songs(1) = "Your Mother Should Know.mid"
			Songs(2) = "While My Guitar Gently Weeps (2).mid"
			Songs(3) = "What Goes On.mid"
			Songs(4) = "Twist And Shout.mid"
			Songs(5) = "The Long And Winding Road.mid"
			Songs(6) = "Something.mid"
			Songs(7) = "Real Love.mid"
			Songs(8) = "Ob-La-Di, Ob-La-Da.mid"
			Songs(9) = "Nowhere Man.mid"
			Songs(10) = "Misery.mid"
			Songs(11) = "Michelle.mid"
			Songs(12) = "Me And My Monkey.mid"
			Songs(13) = "Let It Be.mid"
			Songs(14) = "It Won't Be Long.mid"
			Songs(15) = "In My Life.mid"
			Songs(16) = "I Want to Hold Your Hand.mid"
			Songs(17) = "I Am The Walrus (2).mid"
			Songs(18) = "Here Comes The Sun.mid"
			Songs(19) = "Help;Things We Said Today;Imagine Medley.mid"
			Songs(20) = "Chains.mid"
			Songs(21) = "Boys.mid"
			Songs(22) = "Baby You're A Rich Man.mid"
			Songs(23) = "Any Time At All.mid"
			Songs(24) = "And I Love Her.mid"
			Songs(25) = "All My Loving.mid"
			Songs(26) = "Act Naturally.mid"
			Songs(27) = "A Hard Day's Night.mid"
			Songs(28) = "Two Of Us.mid"
			Songs(29) = "Ticket To Ride.mid"
			Songs(30) = "This Boy.mid"
			Songs(31) = "The Fool On The Hill.mid"
			Songs(32) = "Strawberry Fields Forever.mid"
			Songs(33) = "She's Leaving Home.mid"
			Songs(34) = "She's A Woman.mid"
			Songs(35) = "Revolution.mid"
			Songs(36) = "Oh! Darling.mid"
			Songs(37) = "Norwegian Wood.mid"
			Songs(38) = "Maxwell's Silver Hammer.mid"
			Songs(39) = "Love Me Do.mid"
			Songs(40) = "I Saw Her Standing There.mid"
			Songs(41) = "Honey Pie.mid"
			Songs(42) = "Hey Jude.mid"
			Songs(43) = "Here There And Everywhere.mid"
			Songs(44) = "Got To Get You Into My Life.mid"
			Songs(45) = "From Me To You.mid"
			Songs(46) = "Free As A Bird.mid"
			Songs(47) = "For No One.mid"
			Songs(48) = "Eleanor Rigby.mid"
			Songs(49) = "Carry That Weight.mid"
			Songs(50) = "Can't Buy Me Love.mid"
			Songs(51) = "Birthday.mid"
			Songs(52) = "Because.mid"
			Songs(53) = "All Together Now.mid"
			Songs(54) = "Yesterday.mid"
			Songs(55) = "A Taste Of Honey.mid"
			Songs(56) = "Old Brown Shoes.mid"
			Songs(57) = "No Reply.mid"
			Songs(58) = "Mean Mr. Mustard.mid"
			Songs(59) = "Magical Mystery Tour.mid"
			Songs(60) = "Lucy In The Sky With Diamonds.mid"
			Songs(61) = "Lovely Rita.mid"
			Songs(62) = "Lady Madonna.mid"
			Songs(63) = "I've Just Seen A Face.mid"
			Songs(64) = "Imagine.mid"
			Songs(65) = "If I Fall.mid"
			Songs(66) = "I Will.mid"
			Songs(67) = "I Follow The Sun.mid"
			Songs(68) = "I Don't Want To Spoil The Party.mid"
			Songs(69) = "Honey Don't.mid"
			Songs(70) = "Golden Slumbers.mid"
			Songs(71) = "Get Back.mid"
			Songs(72) = "Fool On The Hill.mid"
			Songs(73) = "Flying.mid"
			Songs(74) = "Fixing A Hole.mid"
			Songs(75) = "Eight Days A Week.mid"
			Songs(76) = "Drive My Car.mid"
			Songs(77) = "Do You Wanna Know A Secret.mid"
			Songs(78) = "Day Tripper.mid"
			Songs(79) = "Come Together.mid"
			Songs(80) = "Black Bird.mid"
			Songs(81) = "Being For The Benefit Of Mr. Kite.mid"
			Songs(82) = "Baby It's You.mid"
			Songs(83) = "And Your Bird Can Sing.mid"
			Songs(84) = "Only A Northern Song.mid"
			Songs(85) = "Paperback Writer.mid"
			Songs(86) = "Yellow Submarine.mid"
			Songs(87) = "With A Little Help From My Friends.mid"
			Songs(88) = "When I'm Sixty-Four.mid"
			Songs(89) = "We Can Work It Out.mid"
			Songs(90) = "Til There Was You.mid"
			Songs(91) = "There's A Place.mid"
			Songs(92) = "The Inner Light.mid"
			Songs(93) = "The End.mid"
			Songs(94) = "Sexy Sadie.mid"
			Songs(95) = "Savory Truffle.mid"
			Songs(96) = "Run For Your Life.mid"
			Songs(97) = "Please Please Me.mid"
			Songs(98) = "Piggies.mid"
			Songs(99) = "Pennylane.mid"
			Songs(100) = "You Never Give Me Your Money.mid"
			Songs(101) = "A Day In The Life.mid"
			Songs(102) = "blackbird.mid"
			Songs(103) = "imagine2.mid"
			Songs(104) = "knockin.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/The Beatles/" & Songs(GetRandom(0, 104))
		Case 36
			ReDim Songs(5)
			Songs(0) = "Drive.mid"
			Songs(1) = "Let's Go.mid"
			Songs(2) = "Just What I Needed.mid"
			Songs(3) = "Good Times Roll.mid"
			Songs(4) = "You Might Think.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/The Cars/" & Songs(GetRandom(0, 4))
		Case 37
			ReDim Songs(5)
			Songs(0) = "Light My Fire.mid"
			Songs(1) = "Love Her Madly.mid"
			Songs(2) = "People Are Strange.mid"
			Songs(3) = "Riders On The Storm.mid"
			Songs(4) = "Roadhouse Blues.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/The Doors/" & Songs(GetRandom(0, 4))
		Case 38
			ReDim Songs(7)
			Songs(0) = "Your Wildest Dreams.mid"
			Songs(1) = "The Voice.mid"
			Songs(2) = "Slipping In A Time Zone.mid"
			Songs(3) = "Nights In White Satin.mid"
			Songs(4) = "I'm Just A Singer In A Rock 'N' Roll Band.mid"
			Songs(5) = "Gemini Dream.mid"
			Songs(6) = "For My Lady.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/The Moody Blues/" & Songs(GetRandom(0, 6))
		Case 39
			ReDim Songs(13)
			Songs(0) = "Angie (2).mid"
			Songs(1) = "Start Me Up.mid"
			Songs(2) = "She's So Cold.mid"
			Songs(3) = "Satisfaction.mid"
			Songs(4) = "Miss You.mid"
			Songs(5) = "Jumpin Jack Flash.mid"
			Songs(6) = "Get Off My Cloud.mid"
			Songs(7) = "Fool To Cry.mid"
			Songs(8) = "Can't Be Seen.mid"
			Songs(9) = "Brown Sugar.mid"
			Songs(10) = "As Tears Go By.mid"
			Songs(11) = "You Can't Always Get What You Want.mid"
			Songs(12) = "Ruby Tuesday.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/The Rolling Stones/" & Songs(GetRandom(0, 12))
		Case 40
			ReDim Songs(2)
			Songs(0) = "Pinball Wizard.mid"
			Songs(1) = "Who Are You.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/The Who/" & Songs(GetRandom(0, 1))
		Case 41
			ReDim Songs(7)
			Songs(0) = "You Got Lucky.mid"
			Songs(1) = "Mary Jane's Last Dance.mid"
			Songs(2) = "Learning To Fly.mid"
			Songs(3) = "Into The Great Wide Open.mid"
			Songs(4) = "Free Fallin'.mid"
			Songs(5) = "Don't Come Around Here No More.mid"
			Songs(6) = "A Face In The Crowd.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Tom Petty & The Heartbreakers/" & Songs(GetRandom(0, 6))
		Case 42
			ReDim Songs(9)
			Songs(0) = "A Secret Love.mid"
			Songs(1) = "Rosanna.mid"
			Songs(2) = "Pamela.mid"
			Songs(3) = "I Won't Hold Back.mid"
			Songs(4) = "Hold The Line.mid"
			Songs(5) = "Georgy Porgy.mid"
			Songs(6) = "Africa.mid"
			Songs(7) = "A Thousand Years.mid"
			Songs(8) = "Somewhere Tonight.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Toto/" & Songs(GetRandom(0, 8))
		Case 43
			ReDim Songs(20)
			Songs(0) = "Your Move.mid"
			Songs(1) = "White Car.mid"
			Songs(2) = "The Clap.mid"
			Songs(3) = "Starship Trooper.mid"
			Songs(4) = "Six Wives Of Henry VIII.mid"
			Songs(5) = "Silent Spring.mid"
			Songs(6) = "Shoot High Aim Low.mid"
			Songs(7) = "Roundabout.mid"
			Songs(8) = "Rhythm Of Love.mid"
			Songs(9) = "Owner Of A Lonely Heart.mid"
			Songs(10) = "Our Song.mid"
			Songs(11) = "Machine Messiah.mid"
			Songs(12) = "Love Will Find A Way.mid"
			Songs(13) = "Long Distance Runaround.mid"
			Songs(14) = "I'm Running.mid"
			Songs(15) = "I'm Alive.mid"
			Songs(16) = "Heart Of Sunrise.mid"
			Songs(17) = "And You And I.mid"
			Songs(18) = "Almost Like Love.mid"
			Songs(19) = "round.mid"
			MIDI = "/Sounds/MIDI/ClassicRock/Yes/" & Songs(GetRandom(0, 19))
		Case 44
			ReDim Songs(18)
			Songs(0) = "tntshort.mid"
			Songs(1) = "tntblood.mid"
			Songs(2) = "tnt-futr.mid"
			Songs(3) = "tntfutr2.mid"
			Songs(4) = "tnt_tc.mid"
			Songs(5) = "ultima2.mid"
			Songs(6) = "teamtnt.mid"
			Songs(7) = "gatedoom.mid"
			Songs(8) = "brntfrag.mid"
			Songs(9) = "bunny.mid"
			Songs(0) = "dm2ttl.mid"
			Songs(1) = "doom.mid"
			Songs(2) = "Doom95.mid"
			Songs(3) = "duke3d.mid"
			Songs(4) = "finaldm.mid"
			Songs(5) = "bmlvl1.mid"
			Songs(6) = "hackers.mid"
			Songs(7) = "hexen.mid"
			MIDI = "/Sounds/MIDI/Doom/" & Songs(GetRandom(0, 17))
		Case 45
			ReDim Songs(31)
			Songs(0) = "addamsfm.mid"
			Songs(1) = "addams.mid"
			Songs(2) = "awhole~2.mid"
			Songs(3) = "axel-f.mid"
			Songs(4) = "bond.mid"
			Songs(5) = "halloween.mid"
			Songs(6) = "timewarp.mid"
			Songs(7) = "tubbell1.mid"
			Songs(8) = "voyager2.mid"
			Songs(9) = "voyager.mid"
			Songs(10) = "xfiles1.mid"
			Songs(11) = "xfiles.mid"
			Songs(12) = "x_files4.mid"
			Songs(13) = "zone.mid"
			Songs(14) = "sttng.mid"
			Songs(15) = "StarWars.mid"
			Songs(16) = "StarTrek.mid"
			Songs(17) = "Muppets.mid"
			Songs(18) = "monkies.mid"
			Songs(19) = "picard.mid"
			Songs(20) = "Rocky.mid"
			Songs(21) = "mission2.mid"
			Songs(22) = "MISSION1.MID"
			Songs(23) = "ds9.mid"
			Songs(24) = "flutsong.mid"
			Songs(25) = "grail.mid"
			Songs(26) = "Chariots of Fire.mid"
			Songs(27) = "bg_short_a.mid"
			Songs(28) = "bg_short.mid"
			Songs(29) = "Gilligan's Island.mid"
			Songs(30) = "Mission Impossible.mid"
			MIDI = "/Sounds/MIDI/Soundtracks/" & Songs(GetRandom(0, 30))
	   Case Else
		   MIDI = "/Sounds/MIDI/CocaCola.mid"
	End Select

	GetSongURL = MIDI
End Function
</script>